### ISSUE TITLE
Fix outdated plugins

### ISSUE THREAD

**Issue by PSSF23** [huawei-noah/streamDM#114]
# Bug Report

## Expected behavior
Successful package compilation

## Observed behavior
Error on all the plugins defined [here](https://github.com/huawei-noah/streamDM/blob/master/project/plugins.sbt) with complete terminal messages below:
```
[info] welcome to sbt 1.3.13 (Oracle Corporation Java 1.8.0_60)
[info] loading global plugins from /.../.sbt/1.0/plugins/project
[info] loading global plugins from /.../.sbt/1.0/plugins
[info] loading project definition from /.../streamDM/project/project
[info] loading settings for project streamdm-build from plugins.sbt ...
[info] loading project definition from /.../streamDM/project
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.typesafe.sbteclipse:sbteclipse-plugin:4.0.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 		com.github.mpeltonen:sbt-idea:1.6.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 		com.orrsella:sbt-sublime:1.1.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 		org.netbeans.nbsbt:nbsbt-plugin:1.1.4 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbteclipse:sbteclipse-plugin;sbtVersion=1.0;scalaVersion=2.12:4.0.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_1.0/4.0.0/sbteclipse-plugin-4.0.0.pom
[error]   not found: /.../.ivy2/local/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/4.0.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/4.0.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/4.0.0/ivys/ivy.xml
[error] Error downloading com.github.mpeltonen:sbt-idea;sbtVersion=1.0;scalaVersion=2.12:1.6.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/github/mpeltonen/sbt-idea_2.12_1.0/1.6.0/sbt-idea-1.6.0.pom
[error]   not found: /.../.ivy2/local/com.github.mpeltonen/sbt-idea/scala_2.12/sbt_1.0/1.6.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.mpeltonen/sbt-idea/scala_2.12/sbt_1.0/1.6.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.github.mpeltonen/sbt-idea/scala_2.12/sbt_1.0/1.6.0/ivys/ivy.xml
[error] Error downloading com.orrsella:sbt-sublime;sbtVersion=1.0;scalaVersion=2.12:1.1.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/orrsella/sbt-sublime_2.12_1.0/1.1.1/sbt-sublime-1.1.1.pom
[error]   not found: /.../.ivy2/local/com.orrsella/sbt-sublime/scala_2.12/sbt_1.0/1.1.1/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.orrsella/sbt-sublime/scala_2.12/sbt_1.0/1.1.1/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.orrsella/sbt-sublime/scala_2.12/sbt_1.0/1.1.1/ivys/ivy.xml
[error] Error downloading org.netbeans.nbsbt:nbsbt-plugin;sbtVersion=1.0;scalaVersion=2.12:1.1.4
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/netbeans/nbsbt/nbsbt-plugin_2.12_1.0/1.1.4/nbsbt-plugin-1.1.4.pom
[error]   not found: /.../.ivy2/local/org.netbeans.nbsbt/nbsbt-plugin/scala_2.12/sbt_1.0/1.1.4/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.netbeans.nbsbt/nbsbt-plugin/scala_2.12/sbt_1.0/1.1.4/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.netbeans.nbsbt/nbsbt-plugin/scala_2.12/sbt_1.0/1.1.4/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbteclipse:sbteclipse-plugin;sbtVersion=1.0;scalaVersion=2.12:4.0.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_1.0/4.0.0/sbteclipse-plugin-4.0.0.pom
[error]   not found: /.../.ivy2/local/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/4.0.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/4.0.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/4.0.0/ivys/ivy.xml
[error] Error downloading com.github.mpeltonen:sbt-idea;sbtVersion=1.0;scalaVersion=2.12:1.6.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/github/mpeltonen/sbt-idea_2.12_1.0/1.6.0/sbt-idea-1.6.0.pom
[error]   not found: /.../.ivy2/local/com.github.mpeltonen/sbt-idea/scala_2.12/sbt_1.0/1.6.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.mpeltonen/sbt-idea/scala_2.12/sbt_1.0/1.6.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.github.mpeltonen/sbt-idea/scala_2.12/sbt_1.0/1.6.0/ivys/ivy.xml
[error] Error downloading com.orrsella:sbt-sublime;sbtVersion=1.0;scalaVersion=2.12:1.1.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/orrsella/sbt-sublime_2.12_1.0/1.1.1/sbt-sublime-1.1.1.pom
[error]   not found: /.../.ivy2/local/com.orrsella/sbt-sublime/scala_2.12/sbt_1.0/1.1.1/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.orrsella/sbt-sublime/scala_2.12/sbt_1.0/1.1.1/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.orrsella/sbt-sublime/scala_2.12/sbt_1.0/1.1.1/ivys/ivy.xml
[error] Error downloading org.netbeans.nbsbt:nbsbt-plugin;sbtVersion=1.0;scalaVersion=2.12:1.1.4
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/netbeans/nbsbt/nbsbt-plugin_2.12_1.0/1.1.4/nbsbt-plugin-1.1.4.pom
[error]   not found: /.../.ivy2/local/org.netbeans.nbsbt/nbsbt-plugin/scala_2.12/sbt_1.0/1.1.4/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.netbeans.nbsbt/nbsbt-plugin/scala_2.12/sbt_1.0/1.1.4/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.netbeans.nbsbt/nbsbt-plugin/scala_2.12/sbt_1.0/1.1.4/ivys/ivy.xml
```

## Steps to reproduce the issue

**Command line**
sbt package

**Data source**
None

**Infrastructure details**
* **Java Version:** 1.8.0_60
* **sbt Version:** 1.3.13
* **Scala Version:** 2.12

**Comment by zhangjiajin** [comment]
PR was accepted.
Thanks, @PSSF23
