### ISSUE TITLE
test shell is bad

### ISSUE THREAD

**Issue by charmby** [huawei-noah/streamDM#96]
Exception in thread "main" java.lang.Exception: -l learner (default: SGDLearner)
Learner to use
-e evaluator (default: BasicClassificationEvaluator)
Evaluator to use
-s streamReader (default: org.apache.spark.streamdm.streams.generators.RandomTreeGenerator)
Stream reader to use
-w resultsWriter (default: PrintStreamWriter)
Stream writer to use
-h shouldPrintHeader
Whether or not to print the evaluator header on the output file

	at com.github.javacliparser.ClassOption.cliStringToObject(ClassOption.java:167)
	at org.apache.spark.streamdm.streamDMJob$.main(streamDMJob.scala:55)
	at org.apache.spark.streamdm.streamDMJob.main(streamDMJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.IllegalArgumentException: Expecting option, found: '–s (FileReader –k 100 –d 60 –f ../data/mydata)'.
	at com.github.javacliparser.Options.setViaCLIString(Options.java:150)
	at com.github.javacliparser.ClassOption.cliStringToObject(ClassOption.java:159)
	... 11 more

**Comment by hmgomes** [comment]
Hi @charmby 

Thanks for the headsup, I am going to work on improving that

Best Regards, 

Heitor
